name: CI

on:
  push:
    branches:
      - main
      - '**/feature/*' # Para rodar ações em qualquer branch que comece com "feature/"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Configurar Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Rodar testes
      run: go test ./...

  # Blocks merging into main branch
  protect-main:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar se há merge direto na main
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" && "${GITHUB_EVENT_NAME}" == "push" ]]; then
          echo "Merge direto na main não permitido"
          exit 1
        fi
