---
version: '3.9'

services:
  adopt-pethub:
    network_mode: "host"
    build:
      context: .
    env_file: .env
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=adopt_pethub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '1223:1223'
